---
- hosts: testservers
  remote_user: ec2-user
  become: yes # Fix 'You need to be root to perform this command.' for ec2-user
  
  tasks:
    - name: Installing Apache
      yum: 
        name: httpd
        state: installed

    - name: Enabling httpd service and start the service
      service: 
        name: httpd
        enabled: yes
        state: started
